dist: bionic
language: node_js
node_js: '8.16'
sudo: required
services:
- docker
notifications:
  email: false
cache:
  directories:
  - node_modules
env:
  global:
  - GIT_SHA=$( git rev-parse HEAD )
  - f [ "$TRAVIS_BRANCH" = "master" ] ; then DOCKERTAG=latest; else DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" | tr -s "[:upper:]" "[:lower:]" ) ; fi
before_install:
- openssl aes-256-cbc -K $encrypted_0c700ab4b9a5_key -iv $encrypted_0c700ab4b9a5_iv -in travis_rsa.enc -out travis_rsa -d
- chmod 0600 travis_rsa
script:
- docker build -t schulcloud/superhero-dashboard:$DOCKERTAG -t schulcloud/superhero-dashboard:$GIT_SHA .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push schulcloud/superhero-dashboard:$DOCKERTAG
- docker push schulcloud/superhero-dashboard:$GIT_SHA
