---
    name: Build and push Docker image
    
    on:
      push:
        branches:
          - master
          - develop
          - feature/*
          - release/*
          - hotfix/*
        tags:
          - '[0-9]*'
    
      pull_request:
    
    jobs:
      build_and_push:
        runs-on: ubuntu-18.04
        if: (contains(github.event.head_commit.message, '[skip ci]') == false) && (github.event_name == 'push')
        steps:
          - uses: actions/checkout@v2
    
          - name: Build image
            run: make build
    
          - name: Log into registry
            run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
          - name: Push image
            run: make push
    
          - name: Cleanup
            run: make clean