name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          allow-licenses: > 
            AGPL-3.0-only,
            LGPL-3.0,
            MIT,
            Apache-2.0,
            BSD-2-Clause,
            BSD-3-Clause,
            ISC,
            X11,
            0BSD,
            GPL-3.0,
            AGPL-3.0
          allow-dependencies-licenses: >
            pkg:npm/lodash.includes@4.3.0,
            pkg:npm/lodash.isinteger@4.0.4,
            pkg:npm/lodash.once@4.1.1
            
