---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: |
         export SC_THEME="default"
         export TZ="Europe/Berlin"
         gulp
         ls -la build
        
      - name: Docker meta Service Name
        id: docker_meta_img
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,enable=false,priority=600
            type=sha,enable=true,priority=600,prefix=
        
      - name: Docker meta Service Name for docker hub
        id: docker_meta_img_hub
        uses: docker/metadata-action@v3
        with:
          images: schulcloud/superhero-dashboard
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_img_hub.outputs.tags }}
          labels: ${{ steps.docker_meta_img_hub.outputs.labels }}
